import Head from "next/head";
import DashboardHome from "./dashboard/DashboardHome";
// import DashboardHome from "./dashboard/DashboardHome";
import SignIn from "./onBoarding/SignIn";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Kuver </title>
        <meta name="description" content="Generated by create next app" />
        {/* <link
          rel="icon"
          type="image/x-icon"
          href="/assets/images/kuver.png"
        ></link> */}
      </Head>
      {/* <SignIn /> */}
      <DashboardHome/>
    </div>
  );
}
